### ISSUE TITLE
Huge FPS drop with FFS

### ISSUE THREAD

**Issue by Gambigobilla** [Lordmau5/FFS-v1.X#27] opened 2015-12-28 21:16 UTC
FancyFluidStorage Version:
Fancy Fluid Storage-1.7.10-1.3.5.60
MinecraftForge Version:
10.13.4.1448 1.7.10
10.13.4.1492 1.7.10
10.13.4.1517 1.7.10
10.13.4.1558 1.7.10
10.13.4.1614 1.7.10
SSP or SMP? (Client or Server):
SSP

I made 9x9x9 water tank in my base, after i build it my fps pummeled. normally i play with 120 fps but with tank it drops to 10 to 20. If i even destroy one block of the tank (so making it invalid) fps returns back to 120.

**Comment by Lordmau5** [comment] 2016-01-16 16:34
Sorry for the late response, but I've been busy updating the mod to 1.8.9.

You can check if the problem remains in v1.4, but I won't fix anything in 1.7.10 anymore, sorry.

**Comment by MrGraphic** [comment] 2016-01-16 22:03
I can confirm that this is valid in 1.4.1. When pumping fluid into tank via BC pipe my FPS drops almost to 0 and chunk updates goes beyond 150 from 0 at that time. Only when pumping in - no issues when tank just "sits" even with fluid inside.

**Comment by Lordmau5** [comment] 2016-01-16 22:17
@MrGraphic I might have a potential fix, but I need someone to test it.
Would you mind hopping our IRC channel on esper.net?
Server: rc.esper.net
Channel: #FFS

**Comment by Lordmau5** [comment] 2016-01-16 22:42
Nevermind, I found out why it is and already took care of it. Please try it with this version and tell me if it's resolved:
-snip-

**Comment by MrGraphic** [comment] 2016-01-16 23:48
Yeah, sorry I was away. So,  did a quick check and seems to be working correctly now.

**Comment by Lordmau5** [comment] 2016-01-17 14:28
Quickly reopening.
@Gambigobilla if you read this, can you try it with the newest 1.7.10 version again, 1.3.6?

**Comment by Gambigobilla** [comment] 2016-01-18 11:15
I'm not available at the moment but when I'm back i'll give an update.

**Comment by Lordmau5** [comment] 2016-01-18 15:15
I'll propose yet another fix once I'm home.
I found a bunch of unnecessary update calls in the TileEntityValve class, so ye...
As well, making the code better in general :)

I'll post 1.3.6.1 in here then, once I got it fixed and built.

**Comment by Lordmau5** [comment] 2016-01-18 19:41
Alright, it's 1.3.7.
Get it from the CurseForge :)

**Comment by Lordmau5** [comment] 2016-01-20 22:37
Also closing this for now.
Someone else responded it went down, and I don't have another answer on here.
So I'll take it as resolved :P

**Closed as completed by Lordmau5** 2016-01-20 22:37 UTC
