### ISSUE TITLE
Crash when forming a tank with TiCon Clear Glass

### ISSUE THREAD

**Issue by FreneticScribbler** [Lordmau5/FFS-v1.X#69] opened 2016-07-24 10:58 UTC
**FancyFluidStorage Version**: 1.9.4-1.6.4-b28

**MinecraftForge Version**: 12.18.0.2010

**Mantle/TiCon Version**: 0.10.3/1.10-2.3.3a

**Client or Server?**:
- [ ] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: Loop of these lines - http://pastebin.com/DFt0C3KW

**What happens / happened?**: Attempted to form a tank that included TiCon Clear glass, as title. Server crashed, and crashes whenever the chunk containing the tank is loaded.

**How can we reproduce it?**: Try building a tank including clear glass...

**Comment by maxpowa** [comment] 2016-07-25 17:12
Can't do anything unless you post the full crash report. Those lines aren't enough to go on.

Edit: Duplicate of #68

**Closed as completed** 2016-07-25 17:13 UTC
Labels: duplicate
