### ISSUE TITLE
Server crash 1.9.4

### ISSUE THREAD

**Issue by MakhnoGK** [Lordmau5/FFS-v1.X#59] opened 2016-06-10 21:13 UTC
**FancyFluidStorage Version**:
1.9.4-1.6.0-b19

**MinecraftForge Version**:
1.9.4-12.17.0.1957

**Client or Server?**:
- [ ] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/jcT4dch4))**:

**What happens / happened?**: FFS can't find method to render some of the blocks I think.

**How can we reproduce it?**:

**Comment by Lordmau5** [comment] 2016-06-10 21:46
Duplicate of #55.
Fix for now: Remove Farseek.

**Closed as completed by Lordmau5** 2016-06-10 21:46 UTC
