### ISSUE TITLE
1.8.9-Particles invisible w/ Weather 2 Mod

### ISSUE THREAD

**Issue by WenXin20** [Lordmau5/FFS-v1.X#39] opened 2016-02-25 00:03 UTC
**FancyFluidStorage Version**: 1.4.5.7.94

**MinecraftForge Version**: 1756
- Client

**What happens / happened?**: Cloud Particles from Weather, Storms, and Tornadoes Mod v2.3.11 are invisible with this mod for some reason.

**How can we reproduce it?**: By getting both ffs, and the weather mod and playing in a world.

**Comment by Lordmau5** [comment] 2016-02-25 11:00
Are the particles visible when you don't look at a tank?
As in, is this problem only there when you have a tank built and look towards it?

**Comment by WenXin20** [comment] 2016-02-25 11:47
No, they're invisible the whole time, even when not looking at a tank

**Comment by Lordmau5** [comment] 2016-02-25 11:47
Can you reproduce this issue in a Minecraft instance with just Forge, FFS and the Weather 2 mod?

**Comment by WenXin20** [comment] 2016-02-25 11:49
I'll try it tonight.

**Comment by WenXin20** [comment] 2016-02-26 00:24
Yes, the same thing happens.

**Comment by Corosauce** [comment] 2016-05-24 06:58
Fixed in my code now, https://github.com/Corosauce/weather2/commit/4bdcc9a100018a9136bbb0e4c29f4c01195ccb78 and https://github.com/Corosauce/CoroUtil/commit/e182321c51b94958a6a1d1a0ce7b26c1e39114b8

a release with this fix is still pending.

**Comment by WenXin20** [comment] 2016-05-24 21:32
Thanks

**Comment by Lordmau5** [comment] 2016-06-27 11:01
Closing this due to already being fixed a month ago in @Corosauce 's code :)

**Closed as completed by Lordmau5** 2016-06-27 11:01 UTC
Labels: bug, fixed in dev, acknowledged
