### ISSUE TITLE
[1.8.9-1.4.5.69] Crash on tank frame breaking event.

### ISSUE THREAD

**Issue by MrGraphic** [Lordmau5/FFS-v1.X#32] opened 2016-01-30 00:00 UTC
Forge .1726
No other mods.

Simple empty tank made out of polished diorite and some glass. Can brake in creative. Braking in survival causes:
https://gist.github.com/MrGraphic/8f81dbc13d7ea4ebb75e

I belive this is related to #29 .

**Comment by topisani** [comment] 2016-01-30 11:34
same crash here. i do not have chisel installed.

**Comment by Lordmau5** [comment] 2016-02-02 10:43
Acknowledged.

I really have to think about the overrides on these methods again... They are not working as intended due to Code-changes in MC 1.8 ...

**Comment by Lordmau5** [comment] 2016-02-04 18:08
Fixed in 1.4.5 :)
http://minecraft.curseforge.com/projects/ffs-fancy-fluid-storage/files/2279977

**Closed as completed by Lordmau5** 2016-02-04 18:08 UTC
Labels: bug
