### ISSUE TITLE
Server startup crash

### ISSUE THREAD

**Issue by cauliflower69** [Lordmau5/FFS-v1.X#58] opened 2016-06-08 17:50 UTC
**FancyFluidStorage Version**: 1.9.4-1.6.0-b19

**MinecraftForge Version**: Forge 12.17.0.1954

**Client or Server?**:
- [ ] Client
- [x ] Server

**Crash Report http://pastebin.com/ibfQSwRc

**What happens / happened?**: Server crashes on startup

**How can we reproduce it?**: Try launching with server

**Comment by maxpowa** [comment] 2016-06-08 18:18
Duplicate of #55

**Comment by Lordmau5** [comment] 2016-06-08 18:44
`FarseekCoreMod (Farseek-1.9.4-1.0.jar)`

Check #55, not our fault, sorry.

**Closed as completed by Lordmau5** 2016-06-08 18:44 UTC

**Comment by cauliflower69** [comment] 2016-06-08 23:53
Thanks
