### ISSUE TITLE
Crash when RotaryCraft/DragonAPI loads before FunkyLocomotion

### ISSUE THREAD

**Issue by DoughnutDev** [Lordmau5/FFS-v1.X#7] opened 2015-07-15 17:58 UTC
http://pastebin.com/qQvHdrm2 - this is on startup

**Comment by maxpowa** [comment] 2015-07-15 18:38
Not reproducible with latest Funky Locomotion and recommended Forge, please try ensuring your Funky Locomotion and Forge versions are up to date.

**Comment by MrGraphic** [comment] 2015-07-15 20:23
This is happening because both FFS and RotaryCraft have a code that prevents frames from interaction with blocks.

**Comment by maxpowa** [comment] 2015-07-15 20:41
We just implement framesapi IMoveCheck. We don't do anything hacky, so it must be on RotaryCraft's end.

**Comment by maxpowa** [comment] 2015-07-15 21:00
Confirmed. This is due to @ReikaKalseki shipping the framesapi in DragonAPI. It's also slightly @rwtema's fault due to not using @API, but less so.

Edit: This is wrong. I was misinformed.

**Comment by ReikaKalseki** [comment] 2015-07-15 21:05
I do not ship the Frames API.

**Comment by maxpowa** [comment] 2015-07-15 21:21
My apologies, I was going off of what I was hearing from testers. It does not appear to be an incompatibility with the latest version of DragonAPI/RotaryCraft. Will look into this more.

**Comment by MrGraphic** [comment] 2015-07-15 21:23
Forcing FFS to load before DragonAPI/RotaryCraft makes it work.

**Comment by maxpowa** [comment] 2015-07-15 22:05
Ah yes, I see now. When Funky Locomotion loads after DragonAPI/RotaryCraft there are issues. Test cases below.

@ReikaKalseki can you comment on this?
FFS/FL both loading after DragonAPI/RotaryCraft: http://hastebin.com/ogodojawit (crashes)
FFS loads before and FL loads after DragonAPI/RotaryCraft: http://hastebin.com/repevaqoda (crashes)
vs
FL loading before DragonAPI/RotaryCraft and FFS loading after: http://hastebin.com/junifonahi (doesn't crash) and FL/FFS both loading before DragonAPI/RotaryCraft: http://hastebin.com/oneqawopeb (doesn't crash)

Control case: FFS loading before FL without DragonAPI/RotaryCraft: http://hastebin.com/emobequzam (doesn't crash)

Note that these crashes are `java.lang.NoClassDefFoundError` and FunkyLocomotion's framesapi is definitely in memory at the time of them.

**Comment by maxpowa** [comment] 2015-07-15 22:22
(Probably more of a bug with DragonAPI/RotaryCraft but changed label for clarity)

**Comment by DoughnutDev** [comment] 2015-07-16 05:01
Thing I don't understand is that I have had funky locomotion and Rekias mods together for a long time, but when adding FFS it just crashes, because doesn't your mod read from FL for the frames API.

**Comment by maxpowa** [comment] 2015-07-16 05:02
I'd imagine you didn't have any mods that actually used framesapi.

**Comment by maxpowa** [comment] 2015-07-16 22:29
Should be fixed in latest DragonAPI.

**Closed as completed by maxpowa** 2015-07-16 22:29 UTC
Labels: bug
